from pydantic import BaseModel, Field
from typing import Optional
from uuid import UUID


class ProjectPlanCreate(BaseModel):
    # project_id is optional — engineers create plans without needing a logistics project
    project_id: Optional[UUID] = None
    custom_project_name: str  # free-text name the engineer writes (required)
    notes: Optional[str] = None
    # project_code is AUTO-GENERATED by the backend (PRO-YYYY-NNNN)


class ProjectPlanUpdate(BaseModel):
    title: Optional[str] = None
    notes: Optional[str] = None
    status: Optional[str] = None


class ProjectPlanItemCreate(BaseModel):
    material_id: UUID
    quantity: float = Field(..., gt=0)
    wear_percentage: float = Field(default=100.0, ge=0, le=100)
    notes: Optional[str] = None


class ProjectPlanItemUpdate(BaseModel):
    quantity: Optional[float] = Field(None, gt=0)
    wear_percentage: Optional[float] = Field(None, ge=0, le=100)
    notes: Optional[str] = None


class SubmitPlanPayload(BaseModel):
    reason: Optional[str] = None


class MaterialPropose(BaseModel):
    name: str
    category: Optional[str] = None
    unit_cost: Optional[float] = None
    notes: Optional[str] = None


class MaterialGroupCreate(BaseModel):
    name: str
    description: Optional[str] = None
    category: Optional[str] = "General"


class MaterialGroupUpdate(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None
    category: Optional[str] = None


class MaterialGroupItemCreate(BaseModel):
    material_id: UUID
    quantity: float = Field(..., gt=0)
    wear_percentage: float = Field(default=100.0, ge=0, le=100)
    notes: Optional[str] = None
